spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "admin"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password
    permit-all-patterns:
      - "/register"
      - "/login"
      - "/graphql"
  graphql:
    graphiql:
      enabled: true
      path: "/graphiql"
      schema-introspection: true
