spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "admin"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: user
      password: password
  graphql:
    graphiql:
      enabled: true
      path: "/graphiql"
      schema-introspection: true

app:
  security:
    patternsPermitted: "/api/v1/register,/api/v1/login"